name = "Your mod name"
author = "Your Name"
prefix = "tag"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0 # Disable git hash versioning

[files]
include = [
    "mod.cpp",
    "README.md",
    "meta.cpp",
    "LICENSE"
]

# uncommenting this will ignore the include folder and check against your P: drive
# [hemtt.build]
# pdrive = "require"

exclude = [
    "*.psd" # Exclude all PSD files
]

[properties]
author = "Your Name"

[hemtt.launch]
workshop = [
    "463939057", # ACE3's Workshop ID | Include other workshop ids here
]

presets = []
dlc = []
optionals = []
parameters = []
